default_stages: [commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-yaml
    - id: check-json
    - id: pretty-format-json
      args: ['--autofix']
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-docstring-first

- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    args: ["--profile", "black", "--line-length=120"]
    entry: isort
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: black
    args: ["--line-length=120"]
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: flake8
    types: [python]
    args: ["--max-line-length=120", "--extend-ignore=F811,E731,E203,E231"]

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.1
  hooks:
    - id: terraform_fmt
    - id: terraform_validate

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
  hooks:
    - id: commitizen
      stages: [commit-msg]
